namespace Fido.Uaf.Shared.AuthenticatorCharacteristics
{
    /// <summary>
    /// Names of assertion schemes are strings with a length of 8 characters.
    /// </summary>
    public static class AssertionSchemes
    {
        /// <summary>
        /// UAF TLV based assertion scheme “UAFV1TLV”
        /// 
        /// This assertion scheme allows the authenticator and the FIDO Server to exchange an
        /// asymmetric authentication key generated by the authenticator.The authenticator MUST
        /// generate a key pair (UAuth.pub/UAuth.priv) to be used with algorithm suites listed in
        /// section Authentication Algorithms(with prefix UAF_ALG). This assertion scheme is using a
        /// compact Tag Length Value(TLV) encoding for the KRD and SignData messages generated by
        /// the authenticators.This is the default assertion scheme for the UAF protocol.
        /// </summary>
        public const string UAFV1TLV = "UAFV1TLV";
    }
}
