using Newtonsoft.Json;

namespace Fido.Uaf.Shared.Messages
{
    /// <summary>
    /// Represents a response generated by a specific Authenticator.
    /// </summary>
    public class AuthenticatorSignAssertion
    {
        /// <summary>
        /// The name of the Assertion Scheme used to encode assertion.
        /// See [UAF Supported Assertion Schemes](https://fidoalliance.org/specs/fido-uaf-v1.0-ps-20141208/fido-uaf-protocol-v1.0-ps-20141208.html#uaf-supported-assertion-schemes) for details.
        /// </summary>
        /// <note>
        /// This AssertionScheme is not part of a signed object and hence considered the suspected AssertionScheme.
        /// </note>
        [JsonProperty("assertionScheme", Required = Required.Always)]
        public string AssertionScheme { get; set; }

        /// <summary>
        /// Contains the assertion containing a signature
        /// generated by `UAuth.priv`, i.e. `TAG_UAFV1_AUTH_ASSERTION`.
        /// </summary>
        /// <remarks>
        /// `base64url(byte[1..4096])`
        /// </remarks>
        [JsonProperty("assertion", Required = Required.Always)]
        public string Assertion { get; set; }

        /// <summary>
        /// Any extensions prepared by the Authenticator.
        /// </summary>
        [JsonProperty("exts", NullValueHandling = NullValueHandling.Ignore)]
        public Extension[] Exts { get; set; }
    }
}
